### ISSUE TITLE
Back to Top / Zurück zum Anfang Link reparieren und verbessern.

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekViewDE#17]
- [X] Den "Zurück zum Anfang" Link durch ein Icon ersetzen
- [X] Funktion herstellen
- [X] Angepinnt machen, sodass er an der Position in der Ecke bleibt beim scrollen.
- [ ] ~~Scrolleffekt mit Javascript umsetzen (nettes Gimmik)~~

**Comment by Nicklas2751** [comment]
Für das JS & Html: https://gist.github.com/Nicklas2751/04bdbb26aea2e9e46672e0a43e244594
So hab ich das auf [meiner Webseite](https://nicklas.wiegandt.eu) gelöst.
