### ISSUE TITLE
Ideen für das Gruppieren der Navigationspunkte und Gruppennamen

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekViewDE#24]
Wer Ideen hat wie man am besten die oberen Menüpunkte gruppieren könnte und welche Gruppennamen da gut passen, kann dies hier kund tun.

**Comment by bagbag** [comment]
* Hilfe
    * Anleitung
    * FAQ
    * Forum

- Neuigkeiten
    - News 
    - Changelogs

**Comment by alex1702** [comment]
Das klingt schonmal nicht schlecht. :)

**Comment by marcelb98** [comment]
* Unterstützen
  * GitHub
  * Spenden

**Comment by alex1702** [comment]
Danke für die Ideen. Ich werde dem mal nachgehen und das so umsetzen.
