### ISSUE TITLE
Option zur Änderung der Downloadpfade

### ISSUE THREAD

**Issue by ilu33** [mediathekview/MediathekViewDE#30]
Hallo,
ich kann mich erinnern, daß es in MV früher eine Option gab, alle heruntergeladenen Dateien in einem Verzeichnis abzulegen. Seit Version 13 legt MV Unterverzeichnisse an, anscheinend nach Konventionen des jeweiligen Senders, und ich kann keine Option finden, um diese Verhalten abzustellen. Hab ich was übersehen? Gibts Möglichkeiten, die Option wieder reinzunehmen?

Abgesehen davon: Es ist super, daß sich Leute gefunden haben, die dieses Projekt am Leben halten! Vielen Dank!

**Comment by Nicklas2751** [comment]
1. Ist dies das Repository für die Webseite
2. Ist das eine Frage für das [Forum](https://forum.mediathekview.de/)

Aber: Ja es gibt eine Option: Einstellungen -> Aufzeichnen und Abspielen -> Set bearbeiten -> Speichern -> Speicherziel -> "einen Unterodner mit dem Thema / Abo-Zielpfad anlegen"
Mehr Infos zum Set in der [Anleitung](https://mediathekview.de/anleitung/#beispiel-speichern).
