### ISSUE TITLE
Downloadbuttons

### ISSUE THREAD

**Issue by mischnic** [mediathekview/MediathekViewDE#34]
Die Knöpfe sollten vielleicht besser "Windows (zip) ", "Linux (tar.gz)" und "OS X (dmg)" heißen. Der Archivtyp hat nicht immer zwangsläufig etwas mit dem Betriebssystem zu tun.

![bildschirmfoto 2018-03-24 um 14 52 06](https://user-images.githubusercontent.com/4586894/37864708-f1619518-2f72-11e8-9b3e-3253570bc268.png)

**Comment by alex1702** [comment]
Wurde mit dem Release 1.8.0 und der Veröffentlichung von MV 13.1.0 eingebaut.
