### ISSUE TITLE
HTTP 503 bei Installation über homebrew-cask

### ISSUE THREAD

**Issue by mrclmh** [mediathekview/MediathekViewDE#38]
Anscheinend werden zur Zeit downloads, die über Homebrew-Cask (welches intern curl verwendet) ausgeführt werden, mit HTTP 503 abgewiesen, siehe auch hier https://github.com/Homebrew/homebrew-cask/pull/50804

Ich habe auch das Problem und auch bei mir funktioniert der download über andere Wege (curl, Browser).
Wisst ihr oder könnt ihr feststellen (z.B. aus access log), warum diese downloads abgelehnt werden?

**Comment by alex1702** [comment]
Ich denke mal homebrew-cask macht zu viele Abfragen. Ich hab den Download mit Limits beschränkt. Habe diese jetzt mal erhöht. kannste nochmal testen?

**Comment by mrclmh** [comment]
Nope, das Problem besteht weiterhin.

    ~ mmoehring$ brew cask install mediathekview
    ==> Satisfying dependencies
    ==> Downloading https://download.mediathekview.de/stabil/MediathekView-13.1.1.dmg

    curl: (22) The requested URL returned error: 503 
    Error: Download failed on Cask 'mediathekview' with message: Download failed: 
    https://download.mediathekview.de/stabil/MediathekView-13.1.1.dmg

**Comment by alex1702** [comment]
Jetzt nochmal bitte. Eventuell lässt du mir auch mal deine IP zukommen an info@mediathekview.de

**Comment by mrclmh** [comment]
Jetzt funktioniert es.
