### ISSUE TITLE
Anpassung Anleitung an MV 13.3.0

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekViewDE#40]
In der [Anleitung](https://mediathekview.de/anleitung/#filme) wird die Filterung der Filmliste noch anhand der Version 13.0.6 erklärt.
Diese sollte an die aktuelle MV-Version angepasst werden.

**Comment by alex1702** [comment]
Eventuell könnten wir auch mal nach Hilfe im Forum fragen. Generell sollte die Anleitung und FAQ mal überprüft und gegenfalls überarbeitet werden.

**Comment by Nicklas2751** [comment]
Nun anpassung an 13.3.0 :D
