### ISSUE TITLE
FAQ "Wenn nichts mehr geht" - Alle Einstellungen zurücksetzen ohne GUI

### ISSUE THREAD

**Issue by ghost** [mediathekview/MediathekViewDE#52]
Im Forum gab's eine Meldung, nach welcher die MV GUI letztlich aufgrund defekter Einstellungsdateien wohl nicht bedient werden konnte
https://forum.mediathekview.de/topic/3096/version-13-5-0-st%C3%BCrzt-pl%C3%B6tzlich-ab-windows-10-1903

Die Fehlermeldung war so wüst, dass ich eine entscheidende Aussage des OP übersehen habe und mich beim Troubleshooting komplett vergaloppiert habe. Alles wäre sehr einfach zu beheben gewesen, hätte man in den FAQ einen Hinweis, wie man die Einstellungen ohne MV GUI zurücksetzt.

Ist dazu ein PR zum Absatz "Wenn nichts geht: Alle Einstellungen zurücksetzen" gewünscht?
https://github.com/me-like-cookies/MediathekViewDE/blob/faq/resettings/content/faq.md

**Comment by derreisende77** [comment]
Ja gerne. Die Erfahrung zeigt zwar das niemand wirklich versucht das Zeug zu lesen, aber schaden tut es nicht wirklich ;-)

**Comment by ghost** [comment]
ok. ich hab einen PR nach develop erstellt.
- oder möchtet Ihr PRs für die Webseite (faq, anleitung etc.) lieber nach master?

**Comment by alex1702** [comment]
>     * oder möchtet Ihr PRs für die Webseite (faq, anleitung etc.) lieber nach master?

Nach develop ist ok.
