### ISSUE TITLE
Platzhalter-Seite mit vollständigererer Seite ersetzten (Theme wechseln)

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MediathekViewDE#7]
Neues Theme wird für #5 und #6 wahrscheinlich eh benötigt.

Theme-Vorschlag: http://themes.gohugo.io/theme/strata/

Braucht eine Anpassung im "Portfolio", die sollte aber fix gemacht sein.

Ich erarbeite den Vorschlag mal in [criztovyl:feature/#7-new-site](https://github.com/criztovyl/MediathekViewDE/tree/feature/%237-new-site).

- [x] Neues Theme hinzufügen
- [ ] Migrieren &rarr; **WIP**
- [ ] Spendenseite hinzufügen, (#5)
- [ ] Über Uns hinzufügen, (#6)

**Comment by alex1702** [comment]
Ich hab da schon was.

**Comment by criztovyl** [comment]
Ukay.

**Comment by criztovyl** [comment]
Dann könn' wir ja später vergleichen welches kuhler ist. :D
